site_name: "Kayode Oluwasegun"

theme:
  name: shadcn
  features:
    - navigation.sections
    - navigation.expand
    - navigation.sidebar

nav:
  - Home: index.md
  - Reading:
      - The Shelf: reading/the-shelf.md
      - Books:
          - Read:
              - "The Go Programming Language": reading/books/read/the-go-programming-language.md
