site_name: "Kayode Oluwasegun"

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.sidebar
  palette:
    - scheme: default
      primary: slate
      accent: teal
    - scheme: slate
      primary: slate
      accent: teal

nav:
  - Home: index.md
  - Reading:
      - The Shelf: reading/the-shelf.md
      - Books:
          - Read:
              - "21 The Go Programming Language": reading/books/read/the-go-programming-language.md
